
big_range = list(range(512))


# CONSTANTS

class BotStates:
    BROADCASTING, \
    SEARCHING, \
    SENDING_KEYWORDS, \
    SENDING_USERNAME, \
    SENDING_NAME, \
    SENDING_EXTRA, \
    SENDING_DESCRIPTION, \
    ADMIN_MENU, \
    DUMMY, \
    ADMIN_ADDING_BOT, \
    EDITING_BOT, \
    *rest = big_range


class CallbackStates:
    SHOWING_BOT_DETAILS, \
    SELECTING_BOT, \
    SELECTING_CATEGORY, \
    APPROVING_BOTS, \
    *rest = big_range


class DeepLinkingActions:
    FAVORITES = 'favorites'
    SEARCH = 'search'
    RULES = 'rules'
    CONTRIBUTING = 'contributing'
    EXAMPLES = 'examples'


class CallbackActions:
    EXPLORE_NEXT, \
    SELECT_MODERATOR, \
    RECOMMEND_MODERATOR, \
    APPLY_ALL_CHANGES, \
    REFRESH_EDIT_BOT, \
    HELP, \
    CHANGE_SUGGESTION, \
    CHANGE_SUGGESTION_TEXT, \
    NONE_ACTION, \
    COUNT_THANK_YOU, \
    CONTRIBUTING, \
    EXAMPLES, \
    ADD_TO_FAVORITES, \
    SEND_FAVORITES_LIST, \
    TOGGLE_FAVORITES_LAYOUT, \
    REMOVE_FAVORITE, \
    ADD_ANYWAY, \
    ADD_FAVORITE, \
    REMOVE_FAVORITE_MENU, \
    INLINE_QUERY_CATEGORIES, \
    EDIT_BOT_SPAM, \
    ABORT_SETTING_KEYWORDS, \
    REMOVE_KEYWORD, \
    EDIT_BOT_KEYWORDS, \
    NEW_BOTS_SELECTED, \
    DISABLE_NOTIFICATIONS, \
    SET_NOTIFICATIONS, \
    SWITCH_APPROVALS_PAGE, \
    SWITCH_SUGGESTIONS_PAGE, \
    REJECT_SUGGESTION, \
    ACCEPT_SUGGESTION, \
    PERMALINK, \
    CONFIRM_DELETE_BOT, \
    DELETE_BOT, \
    EDIT_BOT_OFFLINE, \
    REJECT_BOT, \
    SET_COUNTRY, \
    EDIT_BOT, \
    BOT_ACCEPTED, \
    BACK, \
    ACCEPT_BOT_CAT_SELECTED, \
    ACCEPT_BOT, \
    RESEND_BOTLIST, \
    SELECT_CATEGORY, \
    SEND_BOTLIST, \
    EDIT_BOT_SELECT_BOT, \
    EDIT_BOT_CAT_SELECTED, \
    EDIT_BOT_SELECT_CAT, \
    ADD_BOT_SELECT_CAT, \
    SEND_BOT_DETAILS, \
    SELECT_BOT_FROM_CATEGORY, \
    EDIT_BOT_NAME, \
    EDIT_BOT_USERNAME, \
    EDIT_BOT_DESCRIPTION, \
    EDIT_BOT_COUNTRY, \
    EDIT_BOT_EXTRA, \
    EDIT_BOT_INLINEQUERIES, \
    EDIT_BOT_OFFICIAL, \
    APPROVE_REJECT_BOTS, \
    DELETE_CONVERSATION, \
    DELETE_KEYWORD_SUGGESTION, \
    *rest = big_range


